export { default as HeroSection } from "./components/Sections/HeroSection.svelte";
export {default as Button} from './components/Button.svelte';
export {default as SectionHeadline} from './components/SectionHeadline.svelte';
export {default as AboutMeSection} from './components/Sections/AboutMeSection.svelte';
export { default as ExperienceTable } from './components/ExperienceTable.svelte';
export {default as MyWorkSection} from './components/Sections/MyWorkSection.svelte';
export {default as SkillsSection} from './components/Sections/SkillsSection.svelte';
export {default as ContactSection} from './components/Sections/ContactSection.svelte';
export { default as Header } from './components/Header.svelte';
export (default as Footer) from './components/Footer.svelte';